<?php

namespace App\Entities;

use CodeIgniter\Entity\Entity;

class Fideliz extends Entity
{
    protected $attributes = [
        'id' => null,
        'nivel_fidelidade1' => null,
        'pontos_de1' => null,
        'pontos_ate1' => null,
        'nivel_fidelidade2' => null,
        'pontos_de2' => null,
        'pontos_ate2' => null,
        'nivel_fidelidade3' => null,
        'pontos_de3' => null,
        'pontos_ate3' => null,
        'nivel_fidelidade4' => null,
        'pontos_de4' => null,
        'pontos_ate4' => null,
        'faturamento_pontos1' => null,
        'valor_faturamento_de1' => null,
        'valor_faturamento_ate1' => null,
        'faturamento_pontos2' => null,
        'valor_faturamento_de2' => null,
        'valor_faturamento_ate2' => null,
        'faturamento_pontos3' => null,
        'valor_faturamento_de3' => null,
        'valor_faturamento_ate3' => null,
        'faturamento_pontos4' => null,
        'valor_faturamento_de4' => null,
        'valor_faturamento_ate4' => null,
        'faturamento_pontos5' => null,
        'valor_faturamento_de5' => null,
        'valor_faturamento_ate5' => null,
        'frequencia_pontos1' => null,
        'frequencia_de1' => null,
        'frequencia_ate1' => null,
        'frequencia_pontos2' => null,
        'frequencia_de2' => null,
        'frequencia_ate2' => null,
        'frequencia_pontos3' => null,
        'frequencia_de3' => null,
        'frequencia_ate3' => null,
        'frequencia_pontos4' => null,
        'frequencia_de4' => null,
        'frequencia_ate4' => null,
        'frequencia_pontos5' => null,
        'frequencia_de5' => null,
        'frequencia_ate5' => null,
        'permanencia_pontos1' => null,
        'permanencia_de1' => null,
        'permanencia_ate1' => null,
        'permanencia_pontos2' => null,
        'permanencia_de2' => null,
        'permanencia_ate2' => null,
        'permanencia_pontos3' => null,
        'permanencia_de3' => null,
        'permanencia_ate3' => null,
        'permanencia_pontos4' => null,
        'permanencia_de4' => null,
        'permanencia_ate4' => null,
        'permanencia_pontos5' => null,
        'permanencia_de5' => null,
        'permanencia_ate5' => null,
        'created_at' => null,
        'updated_at' => null,
        'criado_em' => null,
        'editado_em' => null,
    ];

    protected $datamap = [];
    protected $dates   = ['created_at', 'updated_at'];
    protected $casts   = [
        'id' => 'int',
        'pontos_de1' => 'int',
        'pontos_ate1' => 'int',
        'pontos_de2' => 'int',
        'pontos_ate2' => 'int',
        'pontos_de3' => 'int',
        'pontos_ate3' => 'int',
        'pontos_de4' => 'int',
        'pontos_ate4' => 'int',
        'faturamento_pontos1' => 'int',
        'valor_faturamento_de1' => 'int',
        'valor_faturamento_ate1' => 'int',
        'faturamento_pontos2' => 'int',
        'valor_faturamento_de2' => 'int',
        'valor_faturamento_ate2' => 'int',
        'faturamento_pontos3' => 'int',
        'valor_faturamento_de3' => 'int',
        'valor_faturamento_ate3' => 'int',
        'faturamento_pontos4' => 'int',
        'valor_faturamento_de4' => 'int',
        'valor_faturamento_ate4' => 'int',
        'faturamento_pontos5' => 'int',
        'valor_faturamento_de5' => 'int',
        'valor_faturamento_ate5' => 'int',
        'frequencia_pontos1' => 'int',
        'frequencia_de1' => 'int',
        'frequencia_ate1' => 'int',
        'frequencia_pontos2' => 'int',
        'frequencia_de2' => 'int',
        'frequencia_ate2' => 'int',
        'frequencia_pontos3' => 'int',
        'frequencia_de3' => 'int',
        'frequencia_ate3' => 'int',
        'frequencia_pontos4' => 'int',
        'frequencia_de4' => 'int',
        'frequencia_ate4' => 'int',
        'frequencia_pontos5' => 'int',
        'frequencia_de5' => 'int',
        'frequencia_ate5' => 'int',
        'permanencia_pontos1' => 'int',
        'permanencia_de1' => 'int',
        'permanencia_ate1' => 'int',
        'permanencia_pontos2' => 'int',
        'permanencia_de2' => 'int',
        'permanencia_ate2' => 'int',
        'permanencia_pontos3' => 'int',
        'permanencia_de3' => 'int',
        'permanencia_ate3' => 'int',
        'permanencia_pontos4' => 'int',
        'permanencia_de4' => 'int',
        'permanencia_ate4' => 'int',
        'permanencia_pontos5' => 'int',
        'permanencia_de5' => 'int',
        'permanencia_ate5' => 'int'
    ];

    
}