name: 📚 Problema na Documentação
description: Solicitar adições ou melhorias na documentação
labels: "documentation"
body:
  - type: markdown
    attributes:
      value: |
        > 🚨 Se você encontrou um **PROBLEMA RELACIONADO À SEGURANÇA** com o CarolCRM, use o [email](mailto:luizcmarin@gmail.com) para nos reportar quaisquer problemas de segurança que você tenha encontrado. ***AVISO!*** NÃO utilize o rastreador de problemas ou discuta em fóruns públicos, pois isso causará mais dano do que ajuda.
  - type: textarea
    id: id-issue-category
    attributes:
      label: Categoria do Problema
      description: Escolha as opções que melhor descrevem sua sugestão. **Exclua o que não se aplica.**
      value: |
        - Erro de digitação ou sugestão editorial (**Link para a página:**)
        - Informação incorreta/desatualizada (**Link para a página:**)
        - Página/seção/tópico ausente (**Link para a página:**)
        - Não consigo encontrar uma resposta para uma pergunta específica ✔️
        - Sugestão de organização/navegação ✔️
        - Outro ✔️
    validations:
      required: true
  - type: textarea
    id: id-description
    attributes:
      label: Descrição
      description: |
        Descreva o que você esperava encontrar. Inclua também motivação e contexto relevantes.
        Se aplicável, você pode anexar imagens clicando nesta área para destacá-la e depois arrastando os arquivos.
        :warning: _Lembre-se de ocultar ou remover qualquer informação sensível!_
      placeholder: Por favor, coloque detalhes específicos sobre o erro de digitação, erro, informação ausente, sugestão, etc. aqui.
    validations:
      required: true