name: 🚀 Solicitação de Funcionalidade
description: Sugira uma ideia para melhorar o CarolCRM
body:
  - type: textarea
    attributes:
      label: Nova funcionalidade ou mudança proposta
      description: |
        Por favor, forneça uma descrição da funcionalidade ou melhoria.
        Se a funcionalidade for relacionada à interface do usuário, adicione capturas de tela, mockups ou vídeos.
        Se você está solicitando uma implementação de algum padrão ou API, link os recursos relevantes.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Descreva as alternativas que você considerou"
      description: Descreva quaisquer soluções alternativas ou funcionalidades que você considerou.
    validations:
      required: false