<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ConfiguracoesSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['id' => 1,
                 'chave' => 'app_titulo',
                 'categoria' => 'Sistema',
                 'valor' => ' :: olabombinhas',
                 'descricao' => 'Título da aplicação',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 2,
                 'chave' => 'app_versao_maior',
                 'categoria' => 'Sistema',
                 'valor' => '1',
                 'descricao' => 'Número da versão maior',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 3,
                 'chave' => 'app_versao_menor',
                 'categoria' => 'Sistema',
                 'valor' => '4',
                 'descricao' => 'Número da versão menor',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 4,
                 'chave' => 'app_versao_compilacao',
                 'categoria' => 'Sistema',
                 'valor' => '6229',
                 'descricao' => 'Número da compilação',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 5,
                 'chave' => 'app_url',
                 'categoria' => 'Sistema',
                 'valor' => 'https://olabombinhas.com.br',
                 'descricao' => 'URL padrão',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 6,
                 'chave' => 'app_email',
                 'categoria' => 'Sistema',
                 'valor' => 'luizcmarin@gmail.com',
                 'descricao' => 'Email padrão',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 7,
                 'chave' => 'app_titulo_curto',
                 'categoria' => 'Sistema',
                 'valor' => '<b>olabombinhas</b><small class=\"font-14\">.com.br</small>',
                 'descricao' => 'Título curto da aplicação',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 8,
                 'chave' => 'app_logo',
                 'categoria' => 'Sistema',
                 'valor' => 'img/logo-light.png',
                 'descricao' => 'Medidas sugeridas 164px x 122px',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 9,
                 'chave' => 'sem_imagem',
                 'categoria' => 'Sistema',
                 'valor' => '/img/sem-imagem.jpg',
                 'descricao' => '',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 10,
                 'chave' => 'upload_tamanho_maximo_imagem',
                 'categoria' => 'Sistema',
                 'valor' => '1M',
                 'descricao' => null,
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 11,
                 'chave' => 'upload_tamanho_minimo_imagem',
                 'categoria' => 'Sistema',
                 'valor' => '20B',
                 'descricao' => null,
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 12,
                 'chave' => 'sem_foto',
                 'categoria' => 'Sistema',
                 'valor' => '/img/sem-foto.png',
                 'descricao' => '',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 13,
                 'chave' => 'imagem_pessoa_largura',
                 'categoria' => 'Sistema',
                 'valor' => '150',
                 'descricao' => null,
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 14,
                 'chave' => 'imagem_pessoa_altura',
                 'categoria' => 'Sistema',
                 'valor' => '150',
                 'descricao' => null,
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 15,
                 'chave' => 'upload_destino_imagens',
                 'categoria' => 'Sistema',
                 'valor' => '/img/uploads/',
                 'descricao' => '',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 16,
                 'chave' => 'app_pasta_raiz',
                 'categoria' => 'Sistema',
                 'valor' => '/',
                 'descricao' => 'Pasta raiz da aplicação. Inicie e termine com a barra invertida.',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 17,
                 'chave' => 'app_logo_texto',
                 'categoria' => 'Sistema',
                 'valor' => '<p class=\"fs-6 p-0 mb-1\"><b>olabombinhas</b></p><p class=\"fs-7 p-0 mb-0\" style=\"margin-top: -0.8rem;\">.com.br</p>',
                 'descricao' => 'Logo da aplicação em forma de texto',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 18,
                 'chave' => 'app_data_exec_rot_aut',
                 'categoria' => 'Sistema',
                 'valor' => '2022-08-18 11:24:47',
                 'descricao' => 'Data da última execução automática das rotinas internas',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null],
            ['id' => 19,
                 'chave' => 'upload_destino_pdfs',
                 'categoria' => 'Sistema',
                 'valor' => '/img/uploads/pdfs/',
                 'descricao' => 'Pasta onde serão armazenados os pdfs gerados',
                 'sn_sistema' => 'Sim',
                 'tipo' => null,
                 'created_at' => null,
                 'updated_at' => null,
                 'criado_em' => null,
                 'editado_em' => null]
        ];

        // Usando insertBatch para inserir múltiplos registros
        // Ajuste conforme necessário se a tabela tiver gatilhos ou colunas auto-preenchidas
        // $this->db->table('configuracoes')->truncate(); // Descomente para limpar antes de inserir
        if (!empty($data)) {
            $this->db->table('configuracoes')->insertBatch($data);
        } else {
            // Se o array de dados estiver vazio, você pode optar por não fazer nada
            // ou logar uma mensagem.
            // $this->db->table('configuracoes')->where('id IS NOT NULL')->delete(); // Exemplo: limpar a tabela se o seed for vazio
        }
    }
}